FROM ubuntu
MAINTAINER nwoerheide@earlyadopterlabs.com

#RUN apt-get update && DEBIAN_FRONTEND-noninteractive apt-get install -yq apt-utils
#RUN DEBIAN_FRONTEND=nonineractive apt-get install -yq htop

## My Crap ##

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y
